/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Models;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderType {
  Buy, Sell  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderType\",\"namespace\":\"Models\",\"symbols\":[\"Buy\",\"Sell\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
