/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Models;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ActivityType {
  UserProfile, StockTrade  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActivityType\",\"namespace\":\"Models\",\"symbols\":[\"UserProfile\",\"StockTrade\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
