// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class UserInfo : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"UserInfo\",\"namespace\":\"Models\",\"fields\":[{\"name\":\"first\"" +
				",\"type\":\"string\"},{\"name\":\"middle\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"last\"," +
				"\"type\":\"string\"}]}");
		private string _first;
		private string _middle;
		private string _last;
		public virtual Schema Schema
		{
			get
			{
				return UserInfo._SCHEMA;
			}
		}
		public string first
		{
			get
			{
				return this._first;
			}
			set
			{
				this._first = value;
			}
		}
		public string middle
		{
			get
			{
				return this._middle;
			}
			set
			{
				this._middle = value;
			}
		}
		public string last
		{
			get
			{
				return this._last;
			}
			set
			{
				this._last = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.first;
			case 1: return this.middle;
			case 2: return this.last;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.first = (System.String)fieldValue; break;
			case 1: this.middle = (System.String)fieldValue; break;
			case 2: this.last = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
