/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Models;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 689197108096540461L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserInfo\",\"namespace\":\"Models\",\"fields\":[{\"name\":\"First\",\"type\":\"string\"},{\"name\":\"Middle\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"Last\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserInfo> ENCODER =
      new BinaryMessageEncoder<UserInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserInfo> DECODER =
      new BinaryMessageDecoder<UserInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UserInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UserInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UserInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UserInfo from a ByteBuffer. */
  public static UserInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence First;
  @Deprecated public java.lang.CharSequence Middle;
  @Deprecated public java.lang.CharSequence Last;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserInfo() {}

  /**
   * All-args constructor.
   * @param First The new value for First
   * @param Middle The new value for Middle
   * @param Last The new value for Last
   */
  public UserInfo(java.lang.CharSequence First, java.lang.CharSequence Middle, java.lang.CharSequence Last) {
    this.First = First;
    this.Middle = Middle;
    this.Last = Last;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return First;
    case 1: return Middle;
    case 2: return Last;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: First = (java.lang.CharSequence)value$; break;
    case 1: Middle = (java.lang.CharSequence)value$; break;
    case 2: Last = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'First' field.
   * @return The value of the 'First' field.
   */
  public java.lang.CharSequence getFirst() {
    return First;
  }

  /**
   * Sets the value of the 'First' field.
   * @param value the value to set.
   */
  public void setFirst(java.lang.CharSequence value) {
    this.First = value;
  }

  /**
   * Gets the value of the 'Middle' field.
   * @return The value of the 'Middle' field.
   */
  public java.lang.CharSequence getMiddle() {
    return Middle;
  }

  /**
   * Sets the value of the 'Middle' field.
   * @param value the value to set.
   */
  public void setMiddle(java.lang.CharSequence value) {
    this.Middle = value;
  }

  /**
   * Gets the value of the 'Last' field.
   * @return The value of the 'Last' field.
   */
  public java.lang.CharSequence getLast() {
    return Last;
  }

  /**
   * Sets the value of the 'Last' field.
   * @param value the value to set.
   */
  public void setLast(java.lang.CharSequence value) {
    this.Last = value;
  }

  /**
   * Creates a new UserInfo RecordBuilder.
   * @return A new UserInfo RecordBuilder
   */
  public static Models.UserInfo.Builder newBuilder() {
    return new Models.UserInfo.Builder();
  }

  /**
   * Creates a new UserInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserInfo RecordBuilder
   */
  public static Models.UserInfo.Builder newBuilder(Models.UserInfo.Builder other) {
    return new Models.UserInfo.Builder(other);
  }

  /**
   * Creates a new UserInfo RecordBuilder by copying an existing UserInfo instance.
   * @param other The existing instance to copy.
   * @return A new UserInfo RecordBuilder
   */
  public static Models.UserInfo.Builder newBuilder(Models.UserInfo other) {
    return new Models.UserInfo.Builder(other);
  }

  /**
   * RecordBuilder for UserInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserInfo>
    implements org.apache.avro.data.RecordBuilder<UserInfo> {

    private java.lang.CharSequence First;
    private java.lang.CharSequence Middle;
    private java.lang.CharSequence Last;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Models.UserInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.First)) {
        this.First = data().deepCopy(fields()[0].schema(), other.First);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Middle)) {
        this.Middle = data().deepCopy(fields()[1].schema(), other.Middle);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Last)) {
        this.Last = data().deepCopy(fields()[2].schema(), other.Last);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(Models.UserInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.First)) {
        this.First = data().deepCopy(fields()[0].schema(), other.First);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Middle)) {
        this.Middle = data().deepCopy(fields()[1].schema(), other.Middle);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Last)) {
        this.Last = data().deepCopy(fields()[2].schema(), other.Last);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'First' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirst() {
      return First;
    }

    /**
      * Sets the value of the 'First' field.
      * @param value The value of 'First'.
      * @return This builder.
      */
    public Models.UserInfo.Builder setFirst(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.First = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'First' field has been set.
      * @return True if the 'First' field has been set, false otherwise.
      */
    public boolean hasFirst() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'First' field.
      * @return This builder.
      */
    public Models.UserInfo.Builder clearFirst() {
      First = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Middle' field.
      * @return The value.
      */
    public java.lang.CharSequence getMiddle() {
      return Middle;
    }

    /**
      * Sets the value of the 'Middle' field.
      * @param value The value of 'Middle'.
      * @return This builder.
      */
    public Models.UserInfo.Builder setMiddle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Middle = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Middle' field has been set.
      * @return True if the 'Middle' field has been set, false otherwise.
      */
    public boolean hasMiddle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Middle' field.
      * @return This builder.
      */
    public Models.UserInfo.Builder clearMiddle() {
      Middle = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Last' field.
      * @return The value.
      */
    public java.lang.CharSequence getLast() {
      return Last;
    }

    /**
      * Sets the value of the 'Last' field.
      * @param value The value of 'Last'.
      * @return This builder.
      */
    public Models.UserInfo.Builder setLast(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Last = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Last' field has been set.
      * @return True if the 'Last' field has been set, false otherwise.
      */
    public boolean hasLast() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Last' field.
      * @return This builder.
      */
    public Models.UserInfo.Builder clearLast() {
      Last = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserInfo build() {
      try {
        UserInfo record = new UserInfo();
        record.First = fieldSetFlags()[0] ? this.First : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Middle = fieldSetFlags()[1] ? this.Middle : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Last = fieldSetFlags()[2] ? this.Last : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserInfo>
    READER$ = (org.apache.avro.io.DatumReader<UserInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
